environment:
  matrix:
  - julia_version: 1.0.5
  - julia_version: 1.2
  - julia_version: 1.3
  - julia_version: nightly
platform:
  - x64
matrix:
  allow_failures:
  - julia_version: nightly
branches:
  only:
    - master
    - /release-.*/
    - dev
  except:
    - gh-pages
notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))
for:
-
  matrix:
    only:
      - julia_version: 1.3
      - julia_version: nightly
  install:
    - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))
    - ps: Copy-Item C:\julia\libexec\7z.exe C:\julia\bin
build_script:
  - echo "%JL_BUILD_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_BUILD_SCRIPT%"
test_script:
  - echo "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_TEST_SCRIPT%"
